name: SonarQube Analysis

on:
  workflow_dispatch: # This allows the workflow to be run manually
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Begin SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"VacancyBot1" /d:sonar.login=${SONAR_TOKEN}
          dotnet build --no-restore
          dotnet sonarscanner end /d:sonar.login=${SONAR_TOKEN}

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: SonarQube Reports
          path: .scannerwork/report-task.txt
